/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentWorkoutRouteImport } from './routes/student.workout'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNutritionistRouteImport } from './routes/student.nutritionist'
import { Route as StudentEquipmentRouteImport } from './routes/student.equipment'
import { Route as TrainerExercisesRouteImport } from './routes/trainer.exercises'
import { Route as TrainerStudentsIdRouteImport } from './routes/trainer.students.$id'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWorkoutRoute = StudentWorkoutRouteImport.update({
  id: '/student/workout',
  path: '/student/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentNutritionistRoute = StudentNutritionistRouteImport.update({
  id: '/student/nutritionist',
  path: '/student/nutritionist',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEquipmentRoute = StudentEquipmentRouteImport.update({
  id: '/student/equipment',
  path: '/student/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerExercisesRoute = TrainerExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerStudentsIdRoute = TrainerStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => TrainerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/checkin': typeof CheckinRoute
  '/community': typeof CommunityRoute
  '/marketplace': typeof MarketplaceRoute
  '/owner': typeof OwnerRoute
  '/progress': typeof ProgressRoute
  '/schedule': typeof ScheduleRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/student/equipment': typeof StudentEquipmentRoute
  '/student/nutritionist': typeof StudentNutritionistRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/workout': typeof StudentWorkoutRoute
  '/trainer/exercises': typeof TrainerExercisesRoute
  '/trainer/students/$id': typeof TrainerStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/checkin': typeof CheckinRoute
  '/community': typeof CommunityRoute
  '/marketplace': typeof MarketplaceRoute
  '/owner': typeof OwnerRoute
  '/progress': typeof ProgressRoute
  '/schedule': typeof ScheduleRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/student/equipment': typeof StudentEquipmentRoute
  '/student/nutritionist': typeof StudentNutritionistRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/workout': typeof StudentWorkoutRoute
  '/trainer/exercises': typeof TrainerExercisesRoute
  '/trainer/students/$id': typeof TrainerStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/checkin': typeof CheckinRoute
  '/community': typeof CommunityRoute
  '/marketplace': typeof MarketplaceRoute
  '/owner': typeof OwnerRoute
  '/progress': typeof ProgressRoute
  '/schedule': typeof ScheduleRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/student/equipment': typeof StudentEquipmentRoute
  '/student/nutritionist': typeof StudentNutritionistRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/workout': typeof StudentWorkoutRoute
  '/trainer/exercises': typeof TrainerExercisesRoute
  '/trainer/students/$id': typeof TrainerStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/checkin'
    | '/community'
    | '/marketplace'
    | '/owner'
    | '/progress'
    | '/schedule'
    | '/trainer'
    | '/student/equipment'
    | '/student/nutritionist'
    | '/student/profile'
    | '/student/workout'
    | '/trainer/exercises'
    | '/trainer/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/checkin'
    | '/community'
    | '/marketplace'
    | '/owner'
    | '/progress'
    | '/schedule'
    | '/trainer'
    | '/student/equipment'
    | '/student/nutritionist'
    | '/student/profile'
    | '/student/workout'
    | '/trainer/exercises'
    | '/trainer/students/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/checkin'
    | '/community'
    | '/marketplace'
    | '/owner'
    | '/progress'
    | '/schedule'
    | '/trainer'
    | '/student/equipment'
    | '/student/nutritionist'
    | '/student/profile'
    | '/student/workout'
    | '/trainer/exercises'
    | '/trainer/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CheckinRoute: typeof CheckinRoute
  CommunityRoute: typeof CommunityRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OwnerRoute: typeof OwnerRoute
  ProgressRoute: typeof ProgressRoute
  ScheduleRoute: typeof ScheduleRoute
  TrainerRoute: typeof TrainerRouteWithChildren
  StudentEquipmentRoute: typeof StudentEquipmentRoute
  StudentNutritionistRoute: typeof StudentNutritionistRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentWorkoutRoute: typeof StudentWorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/workout': {
      id: '/student/workout'
      path: '/student/workout'
      fullPath: '/student/workout'
      preLoaderRoute: typeof StudentWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/nutritionist': {
      id: '/student/nutritionist'
      path: '/student/nutritionist'
      fullPath: '/student/nutritionist'
      preLoaderRoute: typeof StudentNutritionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/equipment': {
      id: '/student/equipment'
      path: '/student/equipment'
      fullPath: '/student/equipment'
      preLoaderRoute: typeof StudentEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/exercises': {
      id: '/trainer/exercises'
      path: '/exercises'
      fullPath: '/trainer/exercises'
      preLoaderRoute: typeof TrainerExercisesRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/students/$id': {
      id: '/trainer/students/$id'
      path: '/students/$id'
      fullPath: '/trainer/students/$id'
      preLoaderRoute: typeof TrainerStudentsIdRouteImport
      parentRoute: typeof TrainerRoute
    }
  }
}

interface TrainerRouteChildren {
  TrainerExercisesRoute: typeof TrainerExercisesRoute
  TrainerStudentsIdRoute: typeof TrainerStudentsIdRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerExercisesRoute: TrainerExercisesRoute,
  TrainerStudentsIdRoute: TrainerStudentsIdRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CheckinRoute: CheckinRoute,
  CommunityRoute: CommunityRoute,
  MarketplaceRoute: MarketplaceRoute,
  OwnerRoute: OwnerRoute,
  ProgressRoute: ProgressRoute,
  ScheduleRoute: ScheduleRoute,
  TrainerRoute: TrainerRouteWithChildren,
  StudentEquipmentRoute: StudentEquipmentRoute,
  StudentNutritionistRoute: StudentNutritionistRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentWorkoutRoute: StudentWorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
