/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentWorkoutRouteImport } from './routes/student.workout'
import { Route as StudentNutritionistRouteImport } from './routes/student.nutritionist'
import { Route as StudentEquipmentRouteImport } from './routes/student.equipment'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWorkoutRoute = StudentWorkoutRouteImport.update({
  id: '/student/workout',
  path: '/student/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentNutritionistRoute = StudentNutritionistRouteImport.update({
  id: '/student/nutritionist',
  path: '/student/nutritionist',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEquipmentRoute = StudentEquipmentRouteImport.update({
  id: '/student/equipment',
  path: '/student/equipment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/owner': typeof OwnerRoute
  '/trainer': typeof TrainerRoute
  '/student/equipment': typeof StudentEquipmentRoute
  '/student/nutritionist': typeof StudentNutritionistRoute
  '/student/workout': typeof StudentWorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/owner': typeof OwnerRoute
  '/trainer': typeof TrainerRoute
  '/student/equipment': typeof StudentEquipmentRoute
  '/student/nutritionist': typeof StudentNutritionistRoute
  '/student/workout': typeof StudentWorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/owner': typeof OwnerRoute
  '/trainer': typeof TrainerRoute
  '/student/equipment': typeof StudentEquipmentRoute
  '/student/nutritionist': typeof StudentNutritionistRoute
  '/student/workout': typeof StudentWorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marketplace'
    | '/owner'
    | '/trainer'
    | '/student/equipment'
    | '/student/nutritionist'
    | '/student/workout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marketplace'
    | '/owner'
    | '/trainer'
    | '/student/equipment'
    | '/student/nutritionist'
    | '/student/workout'
  id:
    | '__root__'
    | '/'
    | '/marketplace'
    | '/owner'
    | '/trainer'
    | '/student/equipment'
    | '/student/nutritionist'
    | '/student/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OwnerRoute: typeof OwnerRoute
  TrainerRoute: typeof TrainerRoute
  StudentEquipmentRoute: typeof StudentEquipmentRoute
  StudentNutritionistRoute: typeof StudentNutritionistRoute
  StudentWorkoutRoute: typeof StudentWorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/workout': {
      id: '/student/workout'
      path: '/student/workout'
      fullPath: '/student/workout'
      preLoaderRoute: typeof StudentWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/nutritionist': {
      id: '/student/nutritionist'
      path: '/student/nutritionist'
      fullPath: '/student/nutritionist'
      preLoaderRoute: typeof StudentNutritionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/equipment': {
      id: '/student/equipment'
      path: '/student/equipment'
      fullPath: '/student/equipment'
      preLoaderRoute: typeof StudentEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketplaceRoute: MarketplaceRoute,
  OwnerRoute: OwnerRoute,
  TrainerRoute: TrainerRoute,
  StudentEquipmentRoute: StudentEquipmentRoute,
  StudentNutritionistRoute: StudentNutritionistRoute,
  StudentWorkoutRoute: StudentWorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
